---

- name: 'Create user to run Artifactory'
  tags: user
  user:
    name: "{{ artifactory_username }}"
    home: "{{ artifactory_home }}"
    system: true

- name: 'Verify presence of Artifactory distr'
  tags: distr
  stat:
    path: "{{ artifactory_home }}/webapps/artifactory.war"
  register: distr_installed

- name: 'Download Artifactory distr'
  tags: distr
  unarchive:
    src: "{{ artifactory_url }}"
    dest: "{{ artifactory_home }}"
    validate_certs: no
    copy: no
  retries: 3
  when: not distr_installed.stat.exists
  